# Use an official PHP runtime as a parent image
FROM php:8.2-apache

# Install any necessary dependencies
# For example, to install the MySQL extension:
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    && docker-php-ext-install zip \
    && docker-php-ext-install mysqli pdo pdo_mysql

# Copy your PHP application code into the container
COPY . /var/www/html/

# Expose port 80 so that the application is accessible
EXPOSE 80

# (Optional) Set the working directory
RUN echo "ServerName 127.0.0.1" >> /etc/apache2/apache2.conf
WORKDIR /var/www/html/
RUN chown -R www-data:www-data /var/www/html/
RUN chmod -R 755 /var/www/html/

# (Optional) If you have a composer.json file, install dependencies
# RUN apt-get install -y curl && \
#     curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
#     composer install --no-dev --optimize-autoloader

# (Optional) If you need to enable specific Apache modules
# RUN a2enmod rewrite

# Apache configuration (optional)
# Example of changing the document root.
# RUN sed -i 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/000-default.conf
# RUN a2ensite 000-default.conf

# Start Apache (this is the default behavior of the PHP Apache image, but can be added explicitly)
# CMD ["apache2-foreground"]